version: '2'
 
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
    volumes:
      - /var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    restart: always
    build:
      context:  ./app
      dockerfile: Dockerfile
    expose:
      - "8080"
  proxy:
    restart: always
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
